name: db_inspector

description: "A monorepo for db inspector packages"
version: 0.0.1
workspace:
  - packages/db_inspector_core
  - packages/hive_db_inspector
  - packages/flutter_db_inspector
  - packages/shared_preferences_db_inspector
environment:
  sdk: ">=3.5.0 <4.0.0"
# repo-root/pubspec.yaml

dev_dependencies:
  melos: ^7.1.0

